version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend_prod
    ports:
      - "5000:3001"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend_prod
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env.production
    depends_on:
      - backend

