version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=/api

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    volumes:
      - ./backend/downloads:/app/downloads   # downloads をマウント
      - ./backend/uploads:/app/uploads       # uploads をマウント（任意）
